import React from 'react';
export const metadata = {
  title: 'dashboard || Practice next js',
  description: 'Generated by create next app',
}
const SideBar = ({children}) => {
    return (
        <div>
            this is sidebar component
            {children}
        </div>
    );
};

export default SideBar;